kind = "DojoModel"
class_hash = "0x667175337f8ef61e16a7f95b54e4b5a38ed18669027888e34599b174559e52a"
name = "project::models::piece::piece_type"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "piece_stats"
type = "PieceStats"
key = false
