kind = "DojoModel"
class_hash = "0x48483d078ac463323d1a310a56b24c4e20cab9eb0f69456abd974c2f45e0d1a"
name = "project::models::team::team"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "owner"
type = "felt252"
key = false

[[members]]
name = "location"
type = "felt252"
key = false

[[members]]
name = "piece_count"
type = "u8"
key = false

[[members]]
name = "pieces"
type = "Pieces"
key = false

[[members]]
name = "color"
type = "Color"
key = false
