kind = "DojoContract"
class_hash = "0x56cd466df468198612417865089c0d02e2564ec633cb84083813a626995487d"
abi = "abis/base/contracts/gov.json"
reads = []
writes = []
computed = []
name = "project::systems::gov::gov"
