/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@dojoengine/recs";

export function defineContractComponents(world: World) {
  return {
	  Game: (() => {
	    return defineComponent(
	      world,
	      { game_id: RecsType.Number, player_one: RecsType.BigInt, player_two: RecsType.BigInt, ones_turn: RecsType.Boolean },
	      {
	        metadata: {
	          name: "Game",
	          types: ["u32","contractaddress","contractaddress","bool"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  GameManager: (() => {
	    return defineComponent(
	      world,
	      { player: RecsType.BigInt, index: RecsType.Number, game_id: RecsType.Number },
	      {
	        metadata: {
	          name: "GameManager",
	          types: ["contractaddress","u32","u32"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  PieceManager: (() => {
	    return defineComponent(
	      world,
	      { palyer: RecsType.BigInt, index: RecsType.Number, piece: RecsType.Number },
	      {
	        metadata: {
	          name: "PieceManager",
	          types: ["contractaddress","u32","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Player: (() => {
	    return defineComponent(
	      world,
	      { address: RecsType.BigInt, games_count: RecsType.Number, pieces_count: RecsType.Number },
	      {
	        metadata: {
	          name: "Player",
	          types: ["contractaddress","u32","u32"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Secret: (() => {
	    return defineComponent(
	      world,
	      { player: RecsType.BigInt, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Secret",
	          types: ["contractaddress","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
	  Square: (() => {
	    return defineComponent(
	      world,
	      { game_id: RecsType.Number, x: RecsType.Number, y: RecsType.Number, value: RecsType.Number },
	      {
	        metadata: {
	          name: "Square",
	          types: ["u32","u8","u8","u8"],
	          customTypes: [],
	        },
	      }
	    );
	  })(),
  };
}
