kind = "DojoModel"
class_hash = "0x29bf7e0a2a0c4a509aed9df1bf8fb271fafff16c20a9eb802c1b254069cc547"
original_class_hash = "0x29bf7e0a2a0c4a509aed9df1bf8fb271fafff16c20a9eb802c1b254069cc547"
abi = "manifests/dev/abis/base/models/project_models_manager_manager.json"
name = "project::models::manager::manager"

[[members]]
name = "owner"
type = "felt252"
key = true

[[members]]
name = "label"
type = "u8"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "id"
type = "felt252"
key = false
