kind = "DojoModel"
class_hash = "0x2cee661c5ed9e9bcabfc41c758e8ca2aeb83b04ad9b1e7c067acc51c76e4e89"
original_class_hash = "0x2cee661c5ed9e9bcabfc41c758e8ca2aeb83b04ad9b1e7c067acc51c76e4e89"
abi = "manifests/dev/abis/base/models/project_models_game_game.json"
name = "project::models::game::game"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "data"
type = "GameData"
key = false
