kind = "DojoModel"
class_hash = "0x2ee8a8471ff2407510a65a23079967382c38602646c2e887ec36d4890796a7f"
original_class_hash = "0x2ee8a8471ff2407510a65a23079967382c38602646c2e887ec36d4890796a7f"
abi = "manifests/dev/abis/base/models/project_models_manager_player_count.json"
name = "project::models::manager::player_count"

[[members]]
name = "world"
type = "felt252"
key = true

[[members]]
name = "count"
type = "u32"
key = false
