kind = "DojoContract"
class_hash = "0x265ee922d1516dac367c1812ef6f61d1c6d78e9cf1ad630a285b3c3fd129770"
original_class_hash = "0x265ee922d1516dac367c1812ef6f61d1c6d78e9cf1ad630a285b3c3fd129770"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/project_systems_builder_builder.json"
reads = []
writes = []
computed = []
name = "project::systems::builder::builder"
