kind = "DojoContract"
class_hash = "0x783fc92aa9aeb9e014e14f1589728d5524bc2389acfec380e4fe194060ced90"
original_class_hash = "0x783fc92aa9aeb9e014e14f1589728d5524bc2389acfec380e4fe194060ced90"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/project_systems_hub_hub.json"
reads = []
writes = []
computed = []
name = "project::systems::hub::hub"
