[package]
cairo-version = "2.4.0"
name = "project"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", version = "0.4.2" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://0.0.0.0:5050/"
# Default account for katana with seed = 0
account_address = "0x5006399928dad095cc39818cae15dc022592d47d883701e7814c9db19e96efc"
private_key = "0x736adbbcdac7cc600f89051db1abbc16b9996b46f6b58a9752a11c1028a8ec8"
